#!/bin/bash

_SELF="${0##*/}"
_HERE="${0%/${_SELF}}"

declare -a VAULT_AUTH_ARGS

while [ -n "$1" -a "$1" != "--" ]; do
  VAULT_AUTH_ARGS+=($1)
  shift 1
done
shift 1

export VAULT_TOKEN=$("${_HERE}/vault" auth -no-store -token-only "${VAULT_AUTH_ARGS[@]}" 2> /dev/null || exit 1)

exec "$@"
